spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ZlgUZ9jd8GEuOMeWPbWRKLP5ioi1Rfhk
            client-secret: Q_4ewLSaau7aNZ4K5oRfNW4Vhe5WDe74KhFkZuKRXJ2eqT3BlNft8UdcPkdJliWD
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-a1b12a76j5g4edr5.us.auth0.com/